version: '3.7'
networks:
    chatapp_prod_net:
      name: 'capd' 

services:

    aspnet:
        build: .
        restart: always
        container_name: 'chatapp'
        ports:
          - 8000:80
        depends_on:
          - db
        working_dir: '/app'
        networks:
          - chatapp_prod_net
        command: ./wait-for-it.sh chatapp_db:5432 -- dotnet ChatApp.dll   

    db:
        image: 'postgres:12.1'
        container_name: 'chatapp_db'
        restart: always
        networks:
            - chatapp_prod_net     
        environment:
            POSTGRES_DB: chatapp
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 9000:5432

    adminer:
        image: adminer
        restart: always
        networks:
          - chatapp_prod_net    
        ports:
            - 8080:8080
        depends_on:
          - db